// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxgjmefxehxoumsgjpvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Z2ptZWZ4ZWh4b3Vtc2dqcHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjI4MzcsImV4cCI6MjA1NzgzODgzN30.a4NnwL1rR3Mc7m6CIe_DKquZP3Z7JNFL95qqF5Iij1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);